# Numpy

#### 1.Создать вектор (одномерный массив) размера 100, заполненный нулями

In [36]:
import numpy as np
a = np.zeros(100)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


#### 2.Создать вектор размера 100, заполненный единицами

In [37]:
b = np.ones(100)
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


#### 3.Создать вектор размера 100, заполненный числом 3

In [38]:
c = np.full(100, 3.0)
print(c)

[3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3.]


#### 4. Поменять 2 строки в матрице

In [39]:
A = np.arange(100).reshape(10,10)
A[[0,1]] = A[[1,0]]
print(A)

[[10 11 12 13 14 15 16 17 18 19]
 [ 0  1  2  3  4  5  6  7  8  9]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


#### 5. Создать вектор со значениями от 10 до 100

In [40]:
m = np.arange(10,101)
print(m)

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]


#### 6. Создать матрицу (двумерный массив) 4x4 со значениями от 0 до 16

In [41]:
q = np.arange(16).reshape(4,4)
print(q)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 7. Создать 3x3 единичную матрицу

In [42]:
w = np.eye(3)
print(w)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 8. Создать массив 3x3x3 со случайными значениями

In [48]:
y = np.random.random((3,3,3))
print(y)

[[[0.76818699 0.89496072 0.55629896]
  [0.89361362 0.87137458 0.62817206]
  [0.00294792 0.14957182 0.61940137]]

 [[0.33265503 0.17119966 0.52923855]
  [0.95376621 0.21878219 0.87926529]
  [0.56185281 0.00810879 0.17950137]]

 [[0.73847387 0.77615051 0.02828419]
  [0.6538144  0.85112857 0.65323897]
  [0.78362888 0.57196943 0.55005755]]]


#### 9. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [51]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.0004853976491966394 0.9982654732047909


#### 10. Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [55]:
d = np.random.random(30)
m = d.mean()
print(m)

0.49959294832808004


#### 11. Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [65]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 12. Перемножить матрицы 5x3 и 3x2

In [68]:
u = np.dot(np.ones((5,3)), np.ones((3,2)))
print(u)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 13. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [74]:
r = np.arange(10)
r[(3 < r) & (r < 8)] *= -1
print(r)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 14. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [75]:
l = np.zeros((5,5))
l += np.arange(5)
print(l)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 15. Отнять среднее из каждой строки в матрице

In [89]:
X = np.random.rand(5,5)
Y = X - X.mean(axis=1, keepdims=True)
print(X)

[[0.12688776 0.70913547 0.94920342 0.99422848 0.44784053]
 [0.62129577 0.13978479 0.89431378 0.28281058 0.51514307]
 [0.16970845 0.51215155 0.95577094 0.39155781 0.3345507 ]
 [0.45018689 0.99680907 0.99560956 0.44774658 0.60935649]
 [0.9584801  0.34515187 0.57904569 0.6346868  0.99842541]]
